Vagrant.configure(2) do |config|
  config.vm.box = "bento/debian-8.1"
  config.vm.synced_folder "/home/w/apps/dev/vagrant/share", "/share"
  config.vm.provider 'virtualbox' do |v|
    v.cpus = 2
  end
end
