Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-14.04"
  config.vm.synced_folder File.join(File.dirname(__FILE__), "../share"), "/share"
  config.vm.provider 'virtualbox' do |v|
    v.cpus = 2
  end
end
