FROM debian:9

RUN echo 'APT { Install-Recommends "false"; }' |tee /etc/apt/apt.conf.d/40-no-recommends && \
  apt-get update && \
  apt-get install -y gcc git ssh-client python \
    g++ libsnmp-dev libsasl2-dev zlib1g-dev

WORKDIR /app

#ENV GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no' \
#  GIT_SSH='ssh -o StrictHostKeyChecking=no'

RUN mkdir $HOME/.ssh && echo StrictHostKeyChecking no |tee $HOME/.ssh/config

#RUN git clone git@github.com:p-mongo/dev
RUN git config --global http.sslVerify false && \
  git clone https://github.com/p-mongo/dev

RUN mkdir -p /root/apps/exp && git clone https://github.com/mongodb/mongo /root/apps/exp/mongo

RUN apt-get -y install libssl-dev libcurl4-gnutls-dev libldap-dev libkrb5-dev

RUN apt-get -y remove libsensors4

COPY build-mongodb-3.4.sh /build-mongodb-3.4.sh
ENTRYPOINT "/build-mongodb-3.4.sh"

#RUN cd dev && ./script/build-server r3.4.24
