#!/bin/sh

set -e

ticket="$1"
if test -z "$ticket"; then
  ticket=`git branch |grep '^\*' |awk '{print $2}' | sed -e s/'-.*//'`
fi
if test $(basename $(pwd)) = mongoid; then
  project=MONGOID
elif test $(basename $(pwd)) = astrolabe; then
  project=DRIVERS
else
  project=RUBY
fi
git filter-branch -f --msg-filter 'perl -e "undef \$/; \$m=<>; \$m =~ s/^'$project'-\d+ //; \$m =~ s/^/'$project'-'$ticket' /; print \$m"' master..HEAD
