#!/usr/bin/env ruby

require 'find'

Find.find('.') do |path|
  if path.end_with?('.rb')
    c = File.read(path)
    c.sub!(/(\d{4})-\d{4} MongoDB Inc./, '\1-2019 MongoDB Inc.')
    c.sub!(/ (\d{4}) MongoDB Inc./, ' \1-2019 MongoDB Inc.')
    File.open(path, 'w') do |f|
      f << c
    end
  end
end
