#!/usr/bin/env ruby

require 'find'
require 'yaml'

def process(path)
  contents = YAML.load(File.read(path))
  File.open(path, 'w') do |f|
    f << YAML.dump(contents.sub(/\A---\n/, '')
  end
end

ARGV.each do |path|
  if File.directory?(path)
    Find.find(path) do |file_path|
      if file_path =~ /\.ya?ml\z/
        process(file_path)
      end
    end
  else
    process(path)
  end
end
