#!/usr/bin/env perl

use strict;
use warnings;

use File::Temp qw/tempfile tempdir/;
  
sub build {
    my ($project, $branch) = @_;
    
    check_call("git checkout $branch");
    check_call("make publish deploy");
}

sub check_call {
    my ($cmd) = shift;
    my $rv = system($cmd);
    if ($rv != 0) {
        die "Failed to run $cmd";
    }
}

sub doit {
    my $project = shift @ARGV;

    my %branches = (
        'mongoid',
        qw/5.2 6.1 6.2 6.3 6.4 7.0/,
        'ruby',
        qw/v1.x v2.0 v2.2 v2.3 v2.4 v2.5 v2.6 v2.7 v2.8/,
    );

    my $branch = shift @ARGV;

    my @projects;
    if ($project eq '*') {
        @projects = qw/mongoid ruby/;
    } elsif (!$project) {
        @projects = qw/ruby/;
    } elsif ($project eq 'ruby' || $project eq 'mongoid') {
        @projects = ($project);
    } else {
        die "Bogus project: $project";
    }

    my $dir = tempdir(CLEANUP => 1);
    chdir($dir);

    for $project (@projects) {
        check_call("git clone https://github.com/mongodb/docs-$project");
        chdir("docs-$project");
        if ($branch) {
            build($project, $branch);
        } else {
            for $branch ($branches{$project}) {
                build($project, $branch);
            }
        }
        chdir('..');
    }

    chdir('/');
}

doit;
