#!/bin/sh

set -e

ticket="$1"
branch=`git branch |egrep ^'\\*' |awk '{print $2}'`
if test -z "$ticket"; then
  if echo $branch |egrep -iq '^(ruby|mongoid)-[0-9][0-9]*$'; then
    if echo $branch |grep -iq mongoid; then
      project=mongoid
    else
      project=ruby
    fi
    ticket=`echo $branch |sed -e 's/.*-//'`
  else
    echo "Need a ticket as branch $branch is not matching format" 1>&2
    return 5
  fi
else
  if echo $ticket |grep -iq mongoid; then
    project=mongoid
  else
    project=ruby
  fi
  ticket=`echo $ticket |sed -e 's/.*-//'`
fi
jira_project=`echo $project|tr a-z A-Z`
msg=`ruby <<TT
  require 'open-uri'
  require 'json'
  url = "https://jira.mongodb.org/rest/api/2/issue/$jira_project-$ticket"
  payload = JSON.parse(open(url).read)
  puts payload['fields']['summary']
TT`
type=`ruby <<TT
  require 'open-uri'
  require 'json'
  url = "https://jira.mongodb.org/rest/api/2/issue/$jira_project-$ticket"
  payload = JSON.parse(open(url).read)
  puts payload['fields']['issuetype']['name']
TT`
new_msg="$jira_project-$ticket $msg"
if test "$type" = Bug; then
  new_msg="Fix $new_msg"
fi
echo $new_msg
(git branch -D backup || true) &&
git branch backup HEAD &&
git checkout master &&
git pull &&
git checkout $branch &&
git reset --soft $(git merge-base master $branch) && git commit -am "$new_msg" &&
git rebase master &&
git pp $branch -f
