Vagrant.configure(2) do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.synced_folder File.join(File.dirname(__FILE__), '../share'), "/share"
  config.vm.define 'ubuntu'
  config.vm.provider 'libvirt'
end
