Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder File.join(File.dirname(__FILE__), "../share"), "/share"
  config.vm.define 'centos'
  config.vm.provider 'libvirt'
end
